# Generated by Django 4.0.10 on 2024-11-19 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactsubmission_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered with optional '+' and country code. Spaces and hyphens are allowed. Length should be between 7 and 15 digits.", regex='^\\+?(?:[0-9][ -]?){6,14}[0-9]$')], verbose_name='Phone number'),
        ),
    ]
